Improving syntax

diff --git a/src/bin/hanhbuild b/src/bin/hanhbuild
--- a/src/bin/hanhbuild
+++ b/src/bin/hanhbuild
@@ -13,7 +13,7 @@ printf "\n"
 # Help function
 help() {
 echo "hanhbuild - Hanh Linux packages builder"
-echo "Usage: tavbuild [options]"
+echo "Usage: hanhbuild [options]"
 echo "Options"
 echo "--help                                    Print this message"
 echo "--config=<path to config>                 Use a alternative config"
@@ -33,14 +33,23 @@ clean_line(){
 printf "\r                                                 "
 }
 
+# Function for printing infomation
+info() {
+clean_line && printf "\r>> $1"
+}
+
+# Function for printing error
+err() {
+printf "\n>>> $1" && exit 1
+}
+
 # Function for dependencies checking
 depends_check() {
-printf "\r>> Checking dependencies.."
+info "Checking dependencies.."
 if [ ! -z "$depends" ]; then
  for dep in $depends; do
   if [ ! -d $sysroot/var/lib/pachanh/system/$dep ]; then
-   printf "\n>>> $dep not found! Please install and compile it\n"
-   exit 1
+   err "$dep not found! Please install and compile it"
   fi
  done
 fi
@@ -60,58 +69,52 @@ fi
 # Function for working with required buildtime binaries
 bin_check(){
 if [ ! -z "$build_bin" ]; then
- clean_line
- printf "\r>> Checking buildtime binaries..."
+ info "Checking buildtime binaries..."
 
  for binary in $build_bin; do
   for search_dir in $HANH_BINDIR; do
    [ -f $search_dir/$binary ] && final_binary=1 
   done
-[ -z "$final_binary" ] && echo ">>> Binary $binary not found!" && exit 1
+ [ -z "$final_binary" ] && err "Binary $binary not found!"
  done
 
- clean_line
- printf "\r>> Finished binaries check"
+ info "Finished binaries check"
 fi
 }
 
 # Function for working with required runtime libraries
 lib_check() {
-if [ ! -z "$lib" ]; then
- clean_line
- printf "\r>> Checking runtime libraries..."
+if [ ! -z "$lib" ]; then 
+ info "Checking runtime libraries..."
  
  for library in $lib; do
   for search_dir in $HANH_LIBDIR; do
    [ -f "$search_dir/$library" ] && final_lib=1
   done
-  [ -z "$final_lib" ] && echo ">>> Library $library not found!" && exit 1
+  [ -z "$final_lib" ] && err "Library $library not found!"
  done
 
- clean_line
- printf "\r>> Finished libraries check"
+ info "Finished libraries check"
 fi
 }
 
 # Function for checking required files for building packages
 file_check() {
-if [ ! -z "$needed" ]; then
- clean_line
- printf "\r>> Checking files..."
+if [ ! -z "$needed" ]; then 
+ info "Checking files..."
  
  for local_file in $needed; do
-  [ ! -f $hanhdir/$local_file ] && printf "\n>>> File $local_file not found" && exit 1
+  [ ! -f $hanhdir/$local_file ] && err "File $local_file not found"
  done
 
- clean_line
- printf "\r>> Finished files check!"
+ info "Finished files check!"
 fi
 }
 
 # Function for package archive
 archive_pkg(){
 
-echo ">> Finishing package..."
+ info "Finishing package..."
 
 ## Get some useful variables
  pkg_tarball="$name"-"$ver".hanhbuild.tar.gz
@@ -124,7 +127,7 @@ echo ">> Finishing package..."
 
 ## Generate package infomation and local header
  printf "\n"
- printf ">> (0%%)__ Generating information..."
+ info "(0%%)__ Generating information..."
 
  mkdir -p $info_pkgdir
  echo "Name: $name" >> $info_file
@@ -142,21 +145,18 @@ echo ">> Finishing package..."
  echo "contain=\"$contain\"" >> $local_header
  echo "pkg_infodir=\"var/lib/pachanh/system/$name\"" >> $local_header 
 
-## Work with contain line
- clean_line
- printf ">> (5%%)__ Check if the package contain smaller packages..."
+## Work with contain line 
+ info "(5%%)__ Check if the package contain smaller packages..."
  contain_work
 
 ## Generate the filelist.
- clean_line
- printf "\r>> (10%%)_ Generating filelist..."
+ info "(10%%)_ Generating filelist..."
 
  cd $pkgdir
  find * | tee $info_filelist > /dev/null 2>&1
 
 ## Generate the parent header. This header will be removed after the package installation finish.
- clean_line
- printf "\r>> (20%%)_ Generating header..."
+ info "(20%%)_ Generating header..."
  echo "name=\"$name\"" >> $header
  echo "version=\"$ver\"" >> $header
  echo "desc=\"$desc\"" >> $header
@@ -166,19 +166,16 @@ echo ">> Finishing package..."
  echo "pkg_infodir=\"var/lib/pachanh/system/$name\"" >> $header 
 
 ## Compress the package 
- clean_line
- printf "\r>> (30%%)_ Compressing package..."
+ info "(30%%)_ Compressing package..."
  tar -cJf $hanhdir/$pkg_tarball *
  
- clean_line
- printf "\r>> (100%%) Package created: $pkg_tarball" 
+ info "(100%%) Package created: $pkg_tarball" 
 }
 
 # Function for downloading source
 download_source(){
  if [ ! -z "$sources" ]; then
- clean_line
- echo ">> Sources detected! Downloading..."
+ info "Sources detected! Downloading..."
   for need_file in $sources; do
    eval $downloader $need_file
   done
@@ -216,12 +213,12 @@ esac
 done
 
 # Source the configuration file
-[ ! -z "$config" ] && [ ! -f "$config" ] && echo ">>> Configuration file not found!" && exit 1
+[ ! -z "$config" ] && [ ! -f "$config" ] && err "Configuration file not found!"
 [ -z "$config" ] && config="CONFDIR/etc/hanhbuild.conf"
 source $config
 
 if [ ! -z "$override_sysroot" ]; then
- [ ! -d "$override_sysroot" ] && echo ">>> $override_sysroot not found! Exiting..." && exit 1
+ [ ! -d "$override_sysroot" ] && err "$override_sysroot not found! Exiting..."
  sysroot=$override_sysroot
 fi	
 [ -z "$sysroot" ] && sysroot="SYSROOT/"
@@ -229,7 +226,7 @@ fi
 
 # Check if the download command is available.
 [ ! -z "$override_downloader" ] && downloader="$override_downloader"
-[ -z "$downloader" ] && echo ">>> Download command not found" && exit 1
+[ -z "$downloader" ] && err "Download command not found"
 
 # Check if the build file exists then source the build file
 [ -z $buildfile ] && buildfile=buildhanh
@@ -238,8 +235,7 @@ fi
 [ -z "$TAV_LIBDIR" ] && HANH_LIBDIR="/usr/lib /usr/lib64 /lib /lib64"
 
 if [ ! -f $buildfile ]; then
- echo ">>> Build file not found!"
- exit 1
+ err "Build file not found!"
 fi
 
 source $buildfile
@@ -260,12 +256,12 @@ grep_pkg=$(cat $buildfile | grep make-pkg | cut -d "(" -f 1)
 # Execute the functions above with options
 
 if [ "$clean" == 1 ]; then
-printf "\n>> Cleaning necessary directories..."
+info "Cleaning necessary directories..."
 no_unpack=0
 rm -rf $pkgdir $workdir
 fi
 
-printf "\n>> Creating necessary directories if needed..."
+info "Creating necessary directories if needed..."
 mkdir -p $pkgdir $workdir
 
 file_check
@@ -277,22 +273,19 @@ file_check
 [ -z "$grep_compile" ] && repack=1
 
 if [ "$no_unpack" == 0 ]; then
- clean_line
- printf \n">> Unpacking sources..."
+ info "Unpacking sources..."
  unpack-pkg
 fi
 
 if [ "$repack" == 0 ]; then
- printf "\n>> Compiling sources..."
+ info "Compiling sources..."
  compile-pkg
 fi
 
-for repack_command in  $grep_pkg; do
+for repack_command in $grep_pkg; do
  rm -rf $pkgdir && mkdir -p $pkgdir
- clean_line
- printf "\n>> Making package: $name... \n"
+ info "Making package: $name..."
  eval $repack_command
  archive_pkg
 done
 
-printf "\n>> Process executed suscessfully! "
diff --git a/src/bin/hanhinfo b/src/bin/hanhinfo
--- a/src/bin/hanhinfo
+++ b/src/bin/hanhinfo
@@ -7,14 +7,14 @@ trap func_exit EXIT
 
 # Exit function
 func_exit() {
-printf "<< Exiting\n"
+printf "\n"
 }
 
 
 # Function for printing help
 help() {
 echo "hanhinfo - Hanh Linux installed packages search tool"
-echo "Usage: tavinfo [options] [package]"
+echo "Usage: hanhinfo [options] [package]"
 echo "Options"
 echo "--help                                    Print this message"
 echo "--version                                 Print version"
@@ -25,6 +25,14 @@ echo "For any questions, please consider asking on GitHub: https://github.com/ha
 exit
 }
 
+info() {
+printf "\n>> $1"
+}
+
+err() {
+printf "\n>>> $1" && exit 1
+}
+
 # Function for searching packages
 search() {
 for pkg in $package; do
@@ -32,20 +40,19 @@ for pkg in $package; do
  if [[ -d $infodir/$pkg ]]; then
 ### Check if the specified information file exists
   for file in $files; do
-   [ ! -f $infodir/$pkg/$file ] && echo ">>> Specified file not found! Exiting..." && exit
-   echo ">> Printing $file..."
+   [ ! -f $infodir/$pkg/$file ] && err "Specified file not found! Exiting..."
+   info "Printing $file..."
    cat $infodir/$pkg/$file
   done
  else
-  echo ">>> Package not found! Exiting..."
-  exit
+  err "Package not found! Exiting..."
  fi
 done
 }
 
 # Get the command line
 command="$*"
-[ -z "$command" ] && echo ">>> No package specified! Please use 'tavinfo --help' for more information" && exit
+[ -z "$command" ] && err "No package specified! Please use 'hanhinfo --help' for more information"
 
 # Parse the command line
 for x in $command; do
@@ -63,12 +70,12 @@ esac
 done
 
 # Get some variables
-[ ! -z "$config" ] && [ ! -f "$config" ] && echo ">>> Configuration file not found!" && exit 1
+[ ! -z "$config" ] && [ ! -f "$config" ] && err "Configuration file not found!" 
 [ -z "$config" ] && config="CONFDIR/etc/hanh.conf"
 source $config
 
 if [ ! -z "$override_sysroot" ]; then 
- [ ! -d "$override_sysroot" ] && echo ">>> $override_sysroot not found!" && exit 1
+ [ ! -d "$override_sysroot" ] && err "$override_sysroot not found!" && exit 1
  sysroot=$override_sysroot
 fi
 [ -z "$sysroot" ] && sysroot="SYSROOT/"
diff --git a/src/bin/hanhinstall b/src/bin/hanhinstall
--- a/src/bin/hanhinstall
+++ b/src/bin/hanhinstall
@@ -27,7 +27,7 @@ printf "\n>>> $1\n" && exit 1
 help() {
 echo ">> Printing help"
 echo "hanhinstall - Hanh Linux packages installer"
-echo "Usage: hanhinstall [options] [action] package"
+echo "Usage: tavinstall [options] [action] package"
 echo "Action"
 echo "--sync                                    Sync database from remote"
 echo "--search                                  Search for packages"
@@ -65,7 +65,7 @@ lib_check(){
    for search_dir in $HANH_LIBDIR; do
     [ -f "$search_dir/$need_lib" ] && found_lib=1
    done
-   [ -z "$found_lib" ] && err ">>> Library $need_lib not found!"
+   [ -z "$found_lib" ] && err "Library $need_lib not found!"
   done
  fi
 
@@ -124,7 +124,7 @@ printf "\n"
 info "(0%%)__ Cleaning old database..."
 rm -rf *
 ## Download the database for the server
-clean_line
+
 info "(20%%)_ Working with database..."
 for repo_name in $all_repo; do
  repo=$(basename $repo_name)
@@ -163,7 +163,7 @@ else
   done
  done
 fi
-printf "\r>> (100%%)"
+info "(100%%)"
 }
 
 # Function for installing package.
@@ -183,7 +183,6 @@ for pkg in $package; do
 ### Disable dependencies check if the --disable-depends option is enabled
 
  if [ "$check_deps" == 1 ]; then
-  clean_line
   info "(5%%)__ Checking dependencies..."
   depends_check
   lib_check
@@ -194,7 +193,6 @@ for pkg in $package; do
  conflicts_func
 
 ### Get package info directory
- clean_line
  info "(15%%)_ Getting infomation directory..." 
  tar -C $TEMP -xf $pkg $pkg_infodir
 
@@ -203,8 +201,7 @@ for pkg in $package; do
  newfile=$TEMP/$pkg_infodir/filelist 
 
  if [ -f "$oldfile" ]; then
-  clean_line
-  info ">> (20%%)_ Filtering old files..."
+  info "(20%%)_ Filtering old files..."
   difffiles=$(diff $oldfile $newfile | grep "<" | sed 's/< //g')
   for files in $difffiles; do 
    rm -rvf $sysroot/$files
@@ -212,7 +209,6 @@ for pkg in $package; do
  fi
 
 ### Unpack the package to $sysroot
- clean_line
  info "(30%%)_ Installing $name..."
  tar -C $sysroot -xf $pkg
  rm -rf $sysroot/pre-install $TEMP
@@ -234,7 +230,6 @@ for pkg_dir in $package; do
  source $installed_pkg_header
 
 ### Remove files (folders will be ignored because it may delete the necessary folders)
- clean_line
  info "(10%%)_ Removing $pkg_dir..."
  cd $sysroot
  rm -f $(cat $installed_pkg_filelist) > /dev/null 2>&1 || true
@@ -244,7 +239,7 @@ for pkg_dir in $package; do
  rm -rf $installed_infodir/$remove_conflict
  done 
  rm -rf $installed_infodir/$name 
- info "\r>> (100%%)"
+ info "(100%%)"
 
 done
 }
@@ -254,17 +249,15 @@ printf "\n"
 info "(0%%)__ Preparing..."
 cd $build_dir
 parent_dir=$(pwd)
-clean_line
 info "(5%%)__ Building packages..."
 for build_pkg in *; do
  [ -d "$parent_dir"/"$build_pkg" ] && cd $parent_dir/$build_pkg && hanhbuild --disable-depends
 done
-clean_line
-info ">> (80%%)_ Moving packages to all_packages directory..."
+info "(80%%)_ Moving packages to all_packages directory..."
 cd $parent_dir
 mkdir -p all_packages
 mv */*.hanhbuild.tar.gz all_packages/
-info "\r>> (100%%)"
+info "(100%%)"
 }
 
 printf "<< Executing command... \n"
@@ -306,16 +299,16 @@ done
 source $config
 
 [ ! -z "$override_downloader" ] && downloader="$override_downloader"
-[ -z "$downloader" ] && err "Download command not found! Exiting..."
+[ -z "$downloader" ] && err "Download command not found! Exiting..." && exit 127
 
-[ ! -z "$mirror_dir" ] && [ ! -d "$mirror_dir" ] && err "Mirror file not found! Exiting..."
+[ ! -z "$mirror_dir" ] && [ ! -d "$mirror_dir" ] && err "Mirror directory not found! Exiting..."
 [ -z "$mirror_dir" ] && mirror_dir="CONFDIR/etc/hanhmirror.d"
 
 if [ ! -z "$override_sysroot" ]; then
- [ ! -d "$override_sysroot" ] && err ">>> $override_sysroot not found! Exiting..."
+ [ ! -d "$override_sysroot" ] && err "$override_sysroot not found! Exiting..."
  sysroot=$override_sysroot
 fi	
-[ -z "$sysroot" ] && sysroot="SYSROOT"
+[ -z "$sysroot" ] && sysroot="SYSROOT/"
 
 [ -z "$HANH_LIBDIR" ] && HANH_LIBDIR="/lib /lib64 /usr/lib /usr/lib64"
 
